name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pyembree
  - pytest
  - python
  - pyyaml
  - scikit-image
  - scipy
  - tensorboardx
  - torchvision
  - tqdm
  - trimesh
  - pip:
    - h5py
    - plyfile

pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
conda install mkl-service
pip install ipykernel -i https://pypi.tuna.tsinghua.edu.cn/simple